apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minigolf-logs
  namespace: minigolf-beta
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
